
export const indonesianProvinces = [
  { code: "AC", name: "Aceh", name_en: "Aceh" },
  { code: "BA", name: "Bali", name_en: "Bali" },
  { code: "BB", name: "Bangka Belitung", name_en: "Bangka Belitung" },
  { code: "BT", name: "Banten", name_en: "Banten" },
  { code: "BE", name: "Bengkulu", name_en: "Bengkulu" },
  { code: "JK", name: "DKI Jakarta", name_en: "DKI Jakarta" },
  { code: "YO", name: "D.I. Yogyakarta", name_en: "D.I. Yogyakarta" },
  { code: "GO", name: "Gorontalo", name_en: "Gorontalo" },
  { code: "JA", name: "Jambi", name_en: "Jambi" },
  { code: "JB", name: "Jawa Barat", name_en: "West Java" },
  { code: "JT", name: "Jawa Tengah", name_en: "Central Java" },
  { code: "JI", name: "Jawa Timur", name_en: "East Java" },
  { code: "KB", name: "Kalimantan Barat", name_en: "West Kalimantan" },
  { code: "KS", name: "Kalimantan Selatan", name_en: "South Kalimantan" },
  { code: "KT", name: "Kalimantan Tengah", name_en: "Central Kalimantan" },
  { code: "KI", name: "Kalimantan Timur", name_en: "East Kalimantan" },
  { code: "KU", name: "Kalimantan Utara", name_en: "North Kalimantan" },
  { code: "KR", name: "Kepulauan Riau", name_en: "Riau Islands" },
  { code: "LA", name: "Lampung", name_en: "Lampung" },
  { code: "MA", name: "Maluku", name_en: "Maluku" },
  { code: "MU", name: "Maluku Utara", name_en: "North Maluku" },
  { code: "NB", name: "Nusa Tenggara Barat", name_en: "West Nusa Tenggara" },
  { code: "NT", name: "Nusa Tenggara Timur", name_en: "East Nusa Tenggara" },
  { code: "PA", name: "Papua", name_en: "Papua" },
  { code: "PS", name: "Papua Selatan", name_en: "South Papua" },
  { code: "PP", name: "Papua Pegunungan", name_en: "Papua Highlands" },
  { code: "PB", name: "Papua Barat", name_en: "West Papua" },
  { code: "PD", name: "Papua Barat Daya", name_en: "Southwest Papua" },
  { code: "RI", name: "Riau", name_en: "Riau" },
  { code: "SR", name: "Sulawesi Barat", name_en: "West Sulawesi" },
  { code: "SN", name: "Sulawesi Selatan", name_en: "South Sulawesi" },
  { code: "ST", name: "Sulawesi Tengah", name_en: "Central Sulawesi" },
  { code: "SG", name: "Sulawesi Tenggara", name_en: "Southeast Sulawesi" },
  { code: "SA", name: "Sulawesi Utara", name_en: "North Sulawesi" },
  { code: "SB", name: "Sumatera Barat", name_en: "West Sumatra" },
  { code: "SS", name: "Sumatera Selatan", name_en: "South Sumatra" },
  { code: "SU", name: "Sumatera Utara", name_en: "North Sumatra" }
];
